name: Export Shiny app to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      R_KEEP_PKG_SOURCE: yes
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7

      - uses: r-lib/actions/setup-r@v2

      # - uses: rstudio/shiny-workflows/setup-r-package@v1
      #   with:
      #     packages: |
      #       renv
      #       posit-dev/r-shinylive

          # pak::pak(
          #   unique(renv::dependencies(".")$Package)
          # )

      - shell: Rscript {0}
        run: |
          install.packages("shinylive")
          shinylive::export(".", "docs")

      - uses: actions/configure-pages@v6

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - id: deployment
        uses: actions/deploy-pages@v4

